version: 2
updates:
  - package-ecosystem: "npm" # Dependabot handles pnpm workspaces via the npm ecosystem
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
